### ISSUE TITLE
Class "summary.mle2" is not exported [feature request]

### ISSUE THREAD

**Issue by andrechalom** [bbolker/bbmle#10]
**Background:**

I am the developer of a package that extends bbmle classes, and we're having some problems to extend the "summary.mle2" class.

The following class is working as intended:

`setClass("fitsad", representation("mle2", sad="character", distr="character", trunc="numeric"))`

But the following class definition makes `devtools::document()` crash, as it can't find "summary.mle2":

`setClass("summary.sads", representation("summary.mle2", fixed="numeric"))`

**Request:**

Would it be possible for bbmle to export the "summary.mle2" class? I think this might be beneficial for other heavy users of the package, and I see no obvious drawbacks.

**Comment by bbolker** [comment]
I made this change in the development version already (9856e75de413). I don't have definite plans for a new CRAN release, but could certainly try to do it sooner if your package needs it ...

**Comment by andrechalom** [comment]
Thanks a lot! I'm submitting a couple more issues on `bbmle`, all of them have very simple fixes. If they can all make it to bbmle version 1.0.20, this would be a great help for our package and for https://github.com/MoBiodiv/mobsim, which depends on `sads`.

**Comment by andrechalom** [comment]
Hi! Do you have an ETA for releasing a new version? I can help with code / testing / documentation if anything is needed. Thanks for your time!

**Comment by bbolker** [comment]
No reason not to submit to CRAN as soon as testing is done. I'll set up a release-critical issues list to work on.
