### ISSUE TITLE
Use of "representation" is deprecated in R 3.0.0

### ISSUE THREAD

**Issue by andrechalom** [bbolker/bbmle#9]
From setClass help page,

> representation, access, version, S3methods : _All these arguments are deprecated from version 3.0.0 of R and should be avoided_.
> ‘representation’ is an argument inherited from S that included both ‘slots’ and ‘contains’, but the use of the latter two arguments is clearer and recommended.

**Comment by bbolker** [comment]
I'll change this, but ... this code was copied from R's `stats4` package more than 10 years ago, and ironically the internal code in the (core) R package still uses `representation`: https://github.com/wch/r-source/blob/trunk/src/library/stats4/R/mle.R#L19

**Comment by andrechalom** [comment]
It seems like a simple fix. Let me know if I can submit a Pull Request.

**Comment by bbolker** [comment]
fixed already ...
